#SPDX-License-Identifier: MIT-0
---
# tasks file for uv-install
- name: Install dependencies
  command: >
    uv add
    {{ item.name }}
    {% if item.with is defined %}
    {% for w in item.with %}--with {{ w }}{% endfor %}
    {% endif %}
  loop: '{{ dependencies }}'
  tags:
  - uv
  
