#SPDX-License-Identifier: MIT-0
---
# tasks file for openwebui
# add user task

- name: Add user 'openwebui'
  ansible.builtin.user:
    name: openwebui
    system: true
    createhome: true

- name: Place systemd config file
  ansible.builtin.template:
    dest: /etc/systemd/system/openwebui-serve.service
    src: templates/openwebui-serve.service.j2
    mode: "0644"

- name: Run openwebui service
  ansible.builtin.systemd:
    name: openwebui-serve
    state: started
    daemon_reload: true
    enabled: true
