#SPDX-License-Identifier: MIT-0
---
# tasks file for openwebui
# add user task

- name: Add user 'openwebui'
  ansible.builtin.user:
    name: openwebui
    system: true
    createhome: true
    home: "{{ openwebui_home }}"

- name: Install uv
  ansible.builtin.include_role:
    name: uusrc.general.uv
  vars:
    uv_become: true
    uv_become_user: openwebui
    uv_venvs:
      - path: "{{ openwebui_venv }}"
        python: '3.11'
    uv_python_versions: [ '3.11' ]

- name: Install openwebui in venv
  ansible.builtin.command: uv pip install open-webui
  environment:
    VIRTUAL_ENV: "{{ openwebui_venv }}"

- name: Place systemd config file
  ansible.builtin.template:
    dest: /etc/systemd/system/openwebui-serve.service
    src: templates/openwebui-serve.service.j2
    mode: "0644"

- name: Run openwebui service
  ansible.builtin.systemd:
    name: openwebui-serve
    state: started
    daemon_reload: true
    enabled: true
